### ISSUE TITLE
Implement scraper for NeurIPS

### ISSUE THREAD

**Issue by gatheluck** [cvpaperchallenge-alumni/Babel#23]
## Why

https://papers.nips.cc/
neuripsのページもスクレイプする必要がある

## Definition of Done

- 以下のコマンドを実行すると`data/json`下に`neurips<YEAR>_papers.json`が生成され、その中に論文の情報が保存されている。ただし、`<YEAR>` は2023〜2019の範囲では確実に動作をする必要がある（その他の範囲でも動作するのが望ましい）。

```bash
% poetry run python src/scripts/scrape_conference_page.py -c neurips -y <YEAR>
```

- 保存されるJSONの形式は`data/json/cvpr2023_papers.json`と同じ。

## How

- `src.cvf.py`を参考に頑張る

**Comment by Hina39** [comment]
２０２３
3218　　こーど

<html>
<body>

NeurIPS'23 | 26.1% (3218/12343) (67 orals, 378 spotlights and 2773 posters)
-- | --

</body>
</html>

https://github.com/lixin4ever/Conference-Acceptance-Rate

ただよくわからん

２０２２
2671 　https://papercopilot.com/statistics/neurips-statistics/neurips-2022-statistics/



<html>
<body>

NeurIPS'19 | 21.1% (1428/6743) (36 orals, 164 spotlights and 1228 posters) |
NeurIPS'20 | 20.1% (1900/9454) (105 orals, 280 spotlights and 1515 posters) | 
NeurIPS'21 | 25.7% (2344/9122) (55 orals, 260 spotlights and 2029 posters) | 


</body>
</html>


そのほか参考
https://research-p.com/column/1133

**Comment by Hina39** [comment]
INFO:__main__:Successfully parsed 3218 papers.　2023

**Comment by Hina39** [comment]
INFO:__main__:Successfully parsed 2671 papers.　2022
